# Generated by Django 4.2.1 on 2023-06-07 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="MovieData",
            fields=[
                ("title", models.CharField(max_length=200)),
                ("genre", models.CharField(max_length=200)),
                (
                    "index",
                    models.CharField(max_length=200, primary_key=True, serialize=False),
                ),
            ],
        ),
    ]
