# Generated by Django 4.2.1 on 2023-06-07 23:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("moviesearch", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelTable(name="moviedata", table="movie_data",),
    ]
