# Generated by Django 4.2.1 on 2023-06-07 23:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("moviesearch", "0002_alter_moviedata_table"),
    ]

    operations = [
        migrations.AlterModelOptions(name="moviedata", options={"managed": False},),
    ]
